version: '3.8'

services:
  mybank:
    image: mybank_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-plain-snow-a54o6ca5.us-east-2.aws.neon.tech:5432/my_bank_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=my_bank_db_owner
      - SPRING_DATASOURCE_PASSWORD=iQphfrT1c0uW
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET}

volumes:
  pgdata:
